/**
 * Identifier + correlation helpers (docs/39 tracing, docs/17 idempotency).
 *
 * Uses the platform `crypto` global (Node 20+ / Web) so there is no runtime
 * dependency. Entity primary keys are generated by Prisma (`@default(cuid())`)
 * at the DB layer; these helpers are for trace ids, prefixed app-level ids, and
 * idempotency keys that must exist before a row is written.
 */

/** A fresh correlation id for a request/job/tool invocation. */
export function newTraceId(): string {
  return crypto.randomUUID();
}

/** A prefixed, sortable-enough unique id, e.g. `act_4f0c...`. */
export function newId(prefix?: string): string {
  const id = crypto.randomUUID();
  return prefix ? `${prefix}_${id}` : id;
}

/**
 * Deterministic idempotency key from stable parts (docs/17). The same inputs
 * always yield the same key so at-least-once delivery becomes effectively-once.
 */
export function idempotencyKey(...parts: Array<string | number>): string {
  return parts.map((p) => String(p)).join(":");
}
